### PR TITLE
Clang format fixes

### PR DESCRIPTION
**Pull request by springmeyer**
Changes needed to have consistent code formatting (per clang-format) on top of skel forward-port work (#22) per https://github.com/mapbox/dawg-cache/pull/22#issuecomment-334391455

### CODE REVIEW

**Comment by apendleton** [comment]
This bracket style doesn't match anything anyone on the geocoding team uses in any other project, and we're the only ones that touch it regularly so I'm pretty firmly opposed to this set of changes absent a really good reason. Seems like it just introduces friction and opportunity for error with no upside.

**Comment by apendleton** [comment]
Actually, looking at the clang-format docs, if we can change `BreakBeforeBraces` to `BS_Attach` in our copy of the .clang-format file, I'd withdraw my opposition. Everything else looks fine to me.

**Comment by springmeyer** [comment]
@apendleton 👍 I have no strong opinion on the format used, only a desire to provide the tooling here to allow for consistent formatting. (I tested using `Attach` and it looks good: https://github.com/mapbox/dawg-cache/pull/23/commits/3281940c29a24ed19733469d16f1ec9b04566e7d).

Would love a review on #22 and #24 as well - they are broken out to make them somewhat more digestable. Anything look off? If things look good I'll then work to bring them into a single branch and land in master.

**Comment by apendleton** [comment]
Cool, yeah, this looks great. Will have a look at the other two.

**Comment by springmeyer** [comment]
Thanks for the review. Turned out to be better to apply the clang-format changes after clang-tidy, so I've made them in b67d407 to #24 and will close this branch. Next step is to merge #24 into #22.

**Pull request closed without merging**
