### PR TITLE
Trie to Test

### PR DESCRIPTION
**Pull request by aaaandrea**
## Context
A branch for understanding DAWG and testing how we might use fuzzy search

## Next Steps
- [x] Add useful tests that implement some cases for basic traversal changes

### CODE REVIEW

**Comment by springmeyer** [comment]
@aaaandrea I noticed this PR and had a quick look to learn what you are u are up to. Feel free to ignore this comment if you are just experimenting. But I wanted to mention that I noticed that the JS tests are using `throw "string"` where I think you'll want to do `throw new Error("string")` like [here](https://github.com/mapbox/dawg-cache/pull/19/files#diff-60fcfda9a075ef42b4034f066e8afd82R37).

**Comment by aaaandrea** [comment]
Thanks @springmeyer ! Yeah, this is all experimental atm.

**Comment by aaaandrea** [comment]
Purpose of this PR:
 - [ ] write tests for the new cases we care about;
    - [x] build a structure with some words in it, and search for a word that's not in the structure but where the structure contains a word missing a letter (@aaaandrea)
    - [x] build a structure with some words in it, and search for a word that's not in the structure but where the structure contains a word with an extra a letter (@aaaandrea)
    - [x] build a structure with some words in it, and search for a word that's not in the structure but where the structure contains both a word with an extra a letter and a word missing a letter (consensus is that in this scenario we should pick one and return that, but not do both) (@aaaandrea)
    - [ ] test scenarios with multiple insertions or deletions; I think initially we won't handle these at all so they should return nothing, but eventually we may want to handle multiple insertions or deletions as long as they're not in sequence (@aarthykc)

For further information see [here](https://github.com/mapbox/geocoding/issues/158).

**Comment by aaaandrea** [comment]
Merged branch into [return-string](https://github.com/mapbox/dawg-cache/pull/27) work.

**Pull request closed without merging**
